---

- name: Check that you can connect (GET) to a page and it returns a status 200
  hosts: localhost
  tasks:
    - psconfig:
        publish: template.json
        #remote_add: https://10.0.0.1/example.json
        #remote_delete: https://example.com/template.json

      register: stdout
    - debug:
        var: stdout


